In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt

df = pd.read_csv('canada_per_capita_income.csv')
new_df = df.drop(df.columns[1], axis='columns')
c= df.loc[:, df.columns[1]]
reg = linear_model.LinearRegression()
reg.fit(new_df,c)
reg.predict([[2020]])

c:\Users\sanjay\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([41288.69409442])

In [2]:
import pickle

In [4]:
with open('linear_model_pickle','wb') as file:
    pickle.dump(reg,file)

In [5]:
reg.predict([[5000]])

c:\Users\sanjay\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([2510114.61825809])

In [6]:
reg.coef_

array([828.46507522])

In [7]:
reg.intercept_

-1632210.7578554575